// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFc9W-MX0A10e8tHuc-fFMqH5-xwtKX1Y',
    appId: '1:688319571802:android:33c7f481c197f560d43563',
    messagingSenderId: '688319571802',
    projectId: 'ecommerce-a4557',
    storageBucket: 'ecommerce-a4557.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJpBx26cC9eKktO_pFXo5jnt5-2sQKlME',
    appId: '1:688319571802:ios:edb334a619a7c0c1d43563',
    messagingSenderId: '688319571802',
    projectId: 'ecommerce-a4557',
    storageBucket: 'ecommerce-a4557.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaJffhznDS-u_FUrWBPCHq9NgmPB6X4nw',
    appId: '1:688319571802:web:d5662565f0285ca9d43563',
    messagingSenderId: '688319571802',
    projectId: 'ecommerce-a4557',
    authDomain: 'ecommerce-a4557.firebaseapp.com',
    storageBucket: 'ecommerce-a4557.appspot.com',
    measurementId: 'G-PRX4GTY8WC',
  );

}